from yacs.config import CfgNode as CN

_C = CN()

# Drug feature extractor
_C.DRUG = CN()
_C.DRUG.NODE_IN_FEATS = 75

_C.DRUG.PADDING = True

_C.DRUG.HIDDEN_LAYERS = [256, 512,512, 256] 
_C.DRUG.NODE_IN_EMBEDDING = 256
_C.DRUG.MAX_NODES = 300

# Protein feature extractor
_C.PROTEIN = CN()
_C.PROTEIN.NUM_FILTERS = [256, 512,512, 256] 
_C.PROTEIN.EMBEDDING_DIM = 256
_C.PROTEIN.NUM_HEAD = 4
_C.PROTEIN.PADDING = True

# Cascaded Cross-Modal Signal Propagation Fusion
_C.SIGNAL = CN()
_C.SIGNAL.NUM_HEAD = 4
_C.SIGNAL.EMBEDDING_DIM = 256
_C.SIGNAL.NUM_CASCADES = 4
_C.SIGNAL.SIGNAL_DROPOUT_RATE = 0.1

# Pretrained feature dimensions
_C.PRETRAINED = CN()
_C.PRETRAINED.CHEMBERTA_DIM = 384
_C.PRETRAINED.PROTT5_DIM = 1024
_C.PRETRAINED.ESM2_DIM = 1280

# Drug feature fusion
_C.DRUG_FUSION = CN()
_C.DRUG_FUSION.NAME = "SCMAF"
_C.DRUG_FUSION.NUM_HEAD = 4
_C.DRUG_FUSION.DROPOUT_RATE = 0.1

# Protein feature fusion
_C.PROTEIN_FUSION = CN()
_C.PROTEIN_FUSION.NAME = "MPMI"
_C.PROTEIN_FUSION.NUM_HEAD = 4
_C.PROTEIN_FUSION.DROPOUT_RATE = 0.1

# MLP decoder
_C.DECODER = CN()
_C.DECODER.NAME = "MPRC"
_C.DECODER.IN_DIM = 768
_C.DECODER.HIDDEN_DIM = 1536
_C.DECODER.OUT_DIM = 384
_C.DECODER.BINARY = 1
_C.DECODER.DROPOUT_RATE = 0.1
# SOLVER
_C.SOLVER = CN()
_C.SOLVER.MAX_EPOCH = 100
_C.SOLVER.BATCH_SIZE = 64
_C.SOLVER.NUM_WORKERS = 8
_C.SOLVER.LR = 5e-5
_C.SOLVER.USE_LD = True
_C.SOLVER.LR_DECAY = 0.7
_C.SOLVER.FUSION_DROPOUT_RATE = 0.1
_C.SOLVER.DECAY_INTERVAL = 10
_C.SOLVER.WEIGHT_DECAY = 1e-4
_C.SOLVER.SEED = 42


_C.SOLVER.GRADIENT_CLIP_NORM = 1.0
_C.SOLVER.WARMUP_STEPS = 2000
_C.SOLVER.SCHEDULER = "cosine"
_C.SOLVER.ACCUMULATION_STEPS = 1


_C.SOLVER.PATIENCE =8
_C.SOLVER.MIN_DELTA = 0.001
_C.SOLVER.MONITOR = 'auroc'
_C.SOLVER.MODE = 'max'


_C.SOLVER.USE_AMP = True  
_C.SOLVER.AMP_OPT_LEVEL = "O1"  

# RESULT
_C.RESULT = CN()
_C.RESULT.OUTPUT_DIR = r"../output/result/"
_C.RESULT.SAVE_MODEL = True

def get_cfg_defaults():
    return _C.clone()
