from yacs.config import CfgNode as CN

_C = CN()

# Drug feature extractor
_C.DRUG = CN()
_C.DRUG.NODE_IN_FEATS = 75

_C.DRUG.PADDING = True

_C.DRUG.HIDDEN_LAYERS = [256, 512,512, 256]  # 减少药物特征层数
_C.DRUG.NODE_IN_EMBEDDING = 256
_C.DRUG.MAX_NODES = 300

# Protein feature extractor
_C.PROTEIN = CN()
_C.PROTEIN.NUM_FILTERS = [256, 512,512, 256] # 减少蛋白质特征层数
_C.PROTEIN.EMBEDDING_DIM = 256
_C.PROTEIN.NUM_HEAD = 4
_C.PROTEIN.PADDING = True

# CrossIntention feature fusion
# CBIE_CrossAttention feature fusion
_C.CBIE_CROSS_ATTENTION = CN()
_C.CBIE_CROSS_ATTENTION.NUM_HEAD = 4
_C.CBIE_CROSS_ATTENTION.EMBEDDING_DIM = 256
_C.CBIE_CROSS_ATTENTION.NUM_CASCADES = 4
_C.CBIE_CROSS_ATTENTION.CBIE_DROPOUT_RATE = 0.1

# MLP decoder
_C.DECODER = CN()
_C.DECODER.NAME = "DualPathFeatureDecoder"
_C.DECODER.IN_DIM = 768
_C.DECODER.HIDDEN_DIM = 1536
_C.DECODER.OUT_DIM = 384
_C.DECODER.BINARY = 1
_C.DECODER.DROPOUT_RATE = 0.1
# SOLVER
_C.SOLVER = CN()
_C.SOLVER.MAX_EPOCH = 100
_C.SOLVER.BATCH_SIZE = 64
_C.SOLVER.NUM_WORKERS = 8
_C.SOLVER.LR = 5e-5
_C.SOLVER.USE_LD = True
_C.SOLVER.LR_DECAY = 0.7
_C.SOLVER.FUSION_DROPOUT_RATE = 0.1
_C.SOLVER.DECAY_INTERVAL = 10
_C.SOLVER.WEIGHT_DECAY = 1e-4
_C.SOLVER.SEED = 1337

# 稳定化训练参数
_C.SOLVER.GRADIENT_CLIP_NORM = 1.0
_C.SOLVER.WARMUP_STEPS = 2000
_C.SOLVER.SCHEDULER = "cosine"
_C.SOLVER.ACCUMULATION_STEPS = 1

# 添加早停相关参数
_C.SOLVER.PATIENCE =8
_C.SOLVER.MIN_DELTA = 0.001
_C.SOLVER.MONITOR = 'auroc'
_C.SOLVER.MODE = 'max'

# 混合精度训练配置
_C.SOLVER.USE_AMP = True  # 默认启用混合精度训练
_C.SOLVER.AMP_OPT_LEVEL = "O1"  # 混合精度优化级别

# RESULT
_C.RESULT = CN()
_C.RESULT.OUTPUT_DIR = r"../output/result/"
_C.RESULT.SAVE_MODEL = True

def get_cfg_defaults():
    return _C.clone()
